# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dbishop/Documents/GitHub/CA15-Lab-0/lab_0/lab_0.cache/wt [current_project]
set_property parent.project_path C:/Users/dbishop/Documents/GitHub/CA15-Lab-0/lab_0/lab_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/dbishop/Documents/GitHub/CA15-Lab-0/adder.v
  C:/Users/dbishop/Documents/GitHub/CA15-Lab-0/lab0_wrapper.v
}
read_xdc C:/Users/dbishop/Downloads/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/dbishop/Downloads/ZYBO_Master.xdc]

synth_design -top lab0_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef lab0_wrapper.dcp
catch { report_utilization -file lab0_wrapper_utilization_synth.rpt -pb lab0_wrapper_utilization_synth.pb }
